version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: todolist_user
      POSTGRES_PASSWORD: todolist_password
    ports:
      - "5432:5432"